export { default as Header } from './Header/Header'
export { default as Hero } from './Hero/Hero'
export { default as Technologies } from './Technologies/Technologies'
export { default as Projects } from './Projects/Projects'
export { default as Accomplishments } from './Accomplishments/Accomplishments'
export { default as Footer } from './Footer/Footer'